name: Renovate

on:
  workflow_dispatch:
    inputs:
      autodiscoverFilter:
        description: Repository filter for autodiscovery
        required: false
        type: string
        default: ""
  schedule:
    - cron: "0 3 * * *"

jobs:
  renovate:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: read  # Add this line

    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: smoultonjr
          repositories: |
            .github
            docker-immich-1
          permission-contents: write
          permission-pull-requests: write
          permission-actions: read

      - name: Checkout central config
        uses: actions/checkout@v4
        with:
          repository: smoultonjr/.github
          token: ${{ steps.app-token.outputs.token }}

      - name: Run Renovate
        uses: renovatebot/github-action@latest
        with:
          token: ${{ steps.app-token.outputs.token }}
          configurationFile: .github/renovate.json5
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: github
          RENOVATE_AUTODISCOVER: "true"
          RENOVATE_AUTODISCOVER_FILTER: ${{ inputs.autodiscoverFilter }}
